keys:
  - &k8s age103f6jf4nhgwlmnn93al2s342se2awnlcsaxuts8eycffgrdwn5ssd57f28
rules:
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
    - age:
      - *k8s
