---
apiVersion: V1
kind: Namespace
metadata:
  name: grafana-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-operator
  namespace: grafana-system
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/grafana-operator --version 
  ref:
    semver: ">= 5.22.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: grafana-system
spec:
  interval: 12h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chartRef:
    kind: OCIRepository
    name: grafana-operator
---
