apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager.yaml
  # - gateway-api.yaml
  - longhorn.yaml
  # - garage-operator.yaml
  # - alloy-operator.yaml
  # - cloudnative-pg.yaml
  # - grafana-operator.yaml
