apiVersion: v1
kind: Secret
metadata:
    name: database-grafana-password
    namespace: pg
stringData:
    username: ENC[AES256_GCM,data:Fd2DQq6Z1Q==,iv:ehMzmmFFke8M+6L2yddvHqS4VMfgmDXjgg8QKsqO6xc=,tag:rrRUktRkr8JbJx4IyRvIjw==,type:str]
    password: ENC[AES256_GCM,data:LXoTr7I52roI4wffdpZYAlyXqLR5hxP8+a1mqK2IIjWMQ6e4hHTNlXH+dnL8Jndv2Io0X3NqxiKU5qIJvV6sww==,iv:149NQ4L8ki28ySvYfzaM1s4VifHPWaXgtztWnwY+U64=,tag:lZBqx3MPL1YCIp8IPP5z1Q==,type:str]
sops:
    age:
        - recipient: age19akqjue8a6z28csprf9msealft9jj98534jd3fmawelmgwscy44qgacuvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YlRzWlF4b1Z6aTZaTnlF
            OFRPa0hWaE1aV1pZc1AxaVdEV1JsbkNrL1JNCk91QmtVOTZ1UWZCbys1ZjFlRVdZ
            Y1phQWFZSTNHNHh6cDNYb1dlMlUxbkEKLS0tIEJlNlVPMHlhL0xTaWRkdEhpTmhS
            Qmh4RVdRR09waW1RaDlqY1hnL05pZUEKS4CJZexCCXJirMtk0yP6Up0k04hveGn7
            oKzeih82h+becJ5CEkPNudL4sxu0lq5Z2kT7kvu9k1GH9yU857McsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:25:09Z"
    mac: ENC[AES256_GCM,data:zAVWlqpmOqSc80TE72GVkQoIqQ+9u6ruwNsgx4fcsKX1RYgRiaa0plz2/JdHoJIGRTlut5/kQLyhXTG8WeRdZbL4yx6fxPD/0bu6eV0MURjI9xUHjFxpdZZIndHzkA93RwtP2SlcG0H2ZenoPx4EqDst7tlJoFSEb0HqQUJGANQ=,iv:Of8T2VwN0/eoZs27zPnPeNGTvGy7JoJeBubXv959uWM=,tag:Y+27i31PsAStqeEVR3O7EQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
