apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    username: ENC[AES256_GCM,data:pmo=,iv:+dfVnH+/fgPepM0Up5gqqysJxZHWMInfX9OfTmcS52A=,tag:DQaeRIeDqyPUf0ANlaZXrA==,type:str]
    password: ENC[AES256_GCM,data:qpWDHkoxiba+cAblbW9fl3U8MUa8TWTBh6Mcy8XlYtt1e2qG1QoHAtW0ERFdQrSD1ZE9kUCFsTiu1lqT3pOIyS47VRwtBKSkoeV1xC4FyWMFh0kv1yqAM1Ord0Ns,iv:IuAjoimVRJrGoApYGzcF+LrObICf9b6rFM/pWGyikgM=,tag:x0Cyu8b0EqWUYGJ3OtzQKw==,type:str]
sops:
    age:
        - recipient: age19akqjue8a6z28csprf9msealft9jj98534jd3fmawelmgwscy44qgacuvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyOUd4UTFpOEtqeDJ2WFE1
            NHl1OGhRZ3laUm9hdkZhaWZ5V3pUQWJWUjBFCmdaeW1sMjExY3RyWXZBSjIyQ2JX
            MnYwVHA4UncyRmhZdk92c3RFYzFTMGsKLS0tIGF5ZVByNmtXMnM1ZEpPMkNENWMx
            TVhIeDRyaTZOM0RzdUV4MFM5UHJVd0EKIe3LxWakPFujIF+JQCbJKQihZyYbe235
            aoNixtaPe137B14ffj9+Vo3NMO21Z8ol999DJWoLbrxwhOVKd4rq+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T19:41:41Z"
    mac: ENC[AES256_GCM,data:UwezhNWf5PM8tXJI+04BBaIvHWSnkrEs7/uUD1QDtzWNHyy1LM3SH5kNMspFSdEpXObGSE9kHZwpeILp0gaXPn4yV6vlZq4/B5URG8RpiJzLytgvgrYJOOIaG21RrseJG0b2NSQVdkciQDca9WqEb3YI6IKunB20v6ioOglcXHk=,iv:mmD4gW0qhPuiR//bI0YMt5mJEI9HB99XG78AI34rQRE=,tag:+IoxAzYYbRAyqbr1iaArtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
