---
apiVersion: v1
kind: Namespace
metadata:
  name: pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: pg
spec:
  instances: 3
  storage:
    storageClass: longhorn-local-volume
    size: 5Gi
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  managed:
    roles:
      - name: grafana
        ensure: present
        login: true
        createdb: false
        passwordSecret:
          name: database-grafana-password
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: database-grafana
  namespace: pg
spec:
  name: grafana
  owner: grafana
  cluster:
    name: pg
---
