---
apiVersion: v1
kind: Namespace
metadata:
  name: pg
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg
  namespace: pg
spec:
  instances: 3
  storage:
    storageClass: longhorn-local-volume
    size: 5Gi
---
