---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  domain.server: |
      heyk.org:53 {
        file /etc/coredns/custom/heyk.db
        log
        errors
      }
  heyk.db: |
      $ORIGIN heyk.org.
      @         IN  SOA heyk.org. admin.heyk.org. 2502171641 7200 3600 1209600 3600

      @                 IN  A    10.10.20.6
      longhorn.local    IN  A    10.10.20.12
      grafana.local     IN  A    10.10.20.19
      nginx.local       IN  A    10.10.20.11
      *.local           IN  A    10.10.20.6 
