---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  httpRoute:
      spec:
        parentRefs:
          - name: grafana-gateway
            namespace: monitoring
        hostnames:
          - grafana.local.heyk.org
  config:
    log:
      mode: "console"
    security:
      admin_user: root
      admin_password: secret
    database:
          type: "postgres"
          host: "pg-rw.pg.svc.cluster.local:5432"
          name: "grafana"
          user: "grafana"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: database-grafana-password
                      key: password
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: grafanadashboard-sample
  namespace: monitoring
spec:
  resyncPeriod: 30s
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  json: >
    {
      "id": null,
      "title": "Simple Dashboard",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "hideControls": false,
      "graphTooltip": 1,
      "panels": [],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "time_options": [],
        "refresh_intervals": []
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "refresh": "5s",
      "schemaVersion": 17,
      "version": 0,
      "links": []
    }
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: grafana-gateway
  namespace: monitoring
spec:
  addresses:
    - type: IPAddress
      value: 10.10.20.19
  gatewayClassName: cilium
  listeners:
  - allowedRoutes:
      namespaces:
        from: Same
    name: grafana-gw
    port: 443
    protocol: HTTPS
    hostname: "grafana.local.heyk.org"
    tls:
      certificateRefs:
      - kind: Secret
        name: grafana-local-heyk-org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-local-heyk-org
  namespace: monitoring
spec:
  secretName: grafana-local-heyk-org
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - "grafana.local.heyk.org"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: Loki
    type: loki
    access: proxy
    url: http://loki.loki.svc.cluster.local:3100
    isDefault: true
    jsonData:
      maxLines: 1000
---
