---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - cilium-bgp.yaml
  - cluster-issuers.yaml
  - coredns-loadbalancer.yaml
  - coredns-heyk.yaml
  - longhorn-loadbalancer.yaml
  - longhorn-static.yaml
  - garage.yaml
  - loki.yaml
  - cloudnative-pg.yaml
  - grafana.yaml
  - flux-instance.yaml
configMapGenerator:
  - name: helm-values-cilium
    files:
      - values.yaml=./helm-values-cilium.yaml
configurations:
  - nameReference:
      - kind: ConfigMap
        version: v1
        fieldSpecs:
          - path: spec/valuesFrom/name
            kind: HelmRelease
