apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: loki-chunk
  namespace: loki
spec:
  clusterRef:
    name: garage
    namespace: default
  quotas:
    maxSize: 10Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: loki-ruler
  namespace: loki
spec:
  clusterRef:
    name: garage
    namespace: default
  quotas:
    maxSize: 2Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageBucket
metadata:
  name: loki-admin
  namespace: loki
spec:
  clusterRef:
    name: garage
    namespace: default
  quotas:
    maxSize: 2Gi
---
apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageKey
metadata:
  name: loki-access
  namespace: loki
spec:
  clusterRef:
    name: garage
    namespace: default
  bucketPermissions:
    - bucketRef: loki-chunk
      read: true
      write: true
    - bucketRef: loki-ruler
      read: true
      write: true
    - bucketRef: loki-admin
      read: true
      write: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  interval: 10m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: loki
      version: '6.53.x'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 10m

  valuesFrom:
    - kind: Secret
      name: loki-access
      valuesKey: access-key-id
      targetPath: loki.storage.s3.access_key_id

    - kind: Secret
      name: loki-access
      valuesKey: secret-access-key
      targetPath: loki.storage.s3.secret_access_key

  values:
    loki:
      schemaConfig:
        configs:
          - from: "2026-02-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      storage:
        type: s3

        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
          admin: loki-admin

        s3:
          endpoint: https://garage.s3.local.heyk.org
          access_key_id: <TO_REPLACE>
          secret_access_key: <TO_REPLACE>
          region: ca 
          s3forcepathstyle: true
    deploymentMode: Distributed

    # Disable minio storage
    minio:
        enabled: false

    gateway:
      service:
        type: LoadBalancer

    ingester:
      replicas: 3
      zoneAwareReplication:
        enabled: false
    querier:
      replicas: 3
      maxUnavailable: 2
      max_concurrent: 2     
    queryFrontend:
      replicas: 2
      maxUnavailable: 1
    queryScheduler:
      replicas: 2
    distributor:
      replicas: 3
      maxUnavailable: 2
    compactor:
      replicas: 1
    indexGateway:
      replicas: 2
      maxUnavailable: 1

    bloomPlanner:
      replicas: 0
    bloomBuilder:
      replicas: 0
    bloomGateway:
      replicas: 0

    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    singleBinary:
      replicas: 0
