---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-local-volume
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: strict-local
  reclaimPolicy: Retain
