apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  domain.server: |
      heyk.org:53 {
        errors
        health
        ready
        file /etc/coredns/custom/heyk.db
        prometheus :9153
        cache 30
        loop
        reload
        forward . 8.8.8.8
        loadbalance
      }
  heyk.db: |
      heyk.org.        IN    SOA    dns.heyk.org    admin.heyk.org    20201118    7200    3600    1209600    3600
      longhorn.local    IN A        10.10.20.12
      *                 IN A        10.10.20.6
