apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  domain.server: |
      local.heyk.org:53 {
        errors
        health
        ready
        file /etc/coredns/custom/heyk.db
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
      }
  heyk.db: |
      $ORIGIN local.heyk.org.
      $TTL 5m               

      ; =============================== Resource Records ==============================
      @                 IN  SOA     ns.local.heyk.org. rtiger.local.heyk.org. (
                                        2020010510     ; Serial
                                        1d             ; Refresh
                                        2h             ; Retry
                                        4w             ; Expire
                                        1h)            ; Minimum TTL
      @                 IN  A       10.10.20.6       ; Local IPv4 address for example.com.
      @                 IN  NS      ns.local.heyk.org.
      ns                IN  CNAME   @                  
      longhorn          IN A        10.10.20.12
      * IN CNAME @
