---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Secret
metadata:
    name: database-grafana-password-monitoring
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:dGLFtuZ70Q==,iv:brmb6Sc4DaAC5TFGCY5B5qkEAk4s7/H1ZUPmWPAuDzk=,tag:iJJxqpNEFkbMqRY65TxXXg==,type:str]
    password: ENC[AES256_GCM,data:IKh/vhB1nBG1xdtftSpxj7kI3Nh3Dh7rW60e6lHUtnMn1te6GVnkax3ZFfbgnuyO05IX+lYi9zDr6AMeQp2dmA==,iv:yME9gNbZPLaxdGs5KmZ5zg7LAPbxQNEWSVzTh1LiDjc=,tag:msBnSUdx8WemLTCJmnwu2A==,type:str]
sops:
    age:
        - recipient: age103f6jf4nhgwlmnn93al2s342se2awnlcsaxuts8eycffgrdwn5ssd57f28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQW5iVUx6dk15cHE3dk9E
            Q2lhcm9KUnM1K05xR2hZL0pHQWNKaU83K2dzCkJNbllWbHhmeDhrcGxPSVcyQklh
            WVZlbEQ2RkR2NWJoQnhZMmF0aThyalUKLS0tIC9jZVZEYkF5RW5ERVg0SFJJKzJm
            Ui83VHExZ2JXVjBCVDk2WnlRSHZSemsKStESUBNCA9drzCphlLeBgWlvp+6rA9WS
            HCKXCmz8LBhzXAcR8VsbW0dix9PNuoMQnHt/EWKAyZW9ZTQXjFRP1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T23:55:10Z"
    mac: ENC[AES256_GCM,data:hgecOudCXuCjWEknSRMexJcxD/paaQYDJzcempYrJGVXrRJfoj8tdym8q98KCWBczmtmMnaJGiSQKG11PHtbmkyUi8P1DHKRG/L3XjZHKF2ainGj1N1MC9SWufHjttizsmzGK3ubPw2PSDF6+F/Wr8ZIULZLlUdGdbFYxVfMg6s=,iv:AQW+FXYWVnzVaJ341LzSU7I7cE5ZhitSKJepe4lVMlc=,tag:op1rXb63EgLHw8zQLgX9Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
