apiVersion: v1
kind: Secret
metadata:
    name: database-grafana-password-monitoring
    namespace: monitoring
stringData:
    username: ENC[AES256_GCM,data:OiT8O1taog==,iv:jHSrvx+KOMU8yif28TswSEwrZu8dzj5qIh2dSPuzifc=,tag:vf4cvfHUBu1HUYgN2HSpyQ==,type:str]
    password: ENC[AES256_GCM,data:GUiw1iZMH61uYgKOsy9Q6o9BsmqBi6Ix9vAAImWhDyLg3DTqYceMra10JRBeEwOsPxKlqbhduQrkt1wDS+C7ww==,iv:99fc47boLxWe5t1J2tqNYok3+5QfHhx94NCdYQANG2Q=,tag:Cc00Rommb0Ef6fNoj178Fg==,type:str]
sops:
    age:
        - recipient: age19akqjue8a6z28csprf9msealft9jj98534jd3fmawelmgwscy44qgacuvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUd3FUNDhrZW9UR3I3U0ta
            czBaVGxaSndrWjJydHhJbUpjRlRkT2JPNUNnClMwU2J5TzJoOVpwRmVGS1hITUVw
            MDh1OStMQTlCT0RQUkE5bUMyOWRZaHMKLS0tIFVUMllBcllhaE9JeEc2OGVKZkE4
            MUVHYXo5dk0wbHp5YWFvRkdlTHo3Z1EK39ITBpppWvBa4Rv7kvtocA1J7sIa3imW
            aL+zzUfwCFDcuKOoAazOGsBSlJnedLp7KbHeud6nukmZaEokncacQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:28:30Z"
    mac: ENC[AES256_GCM,data:VqsaWRHlnGaM73wfey7E+eBEbWYSuTFYtzh1wCSzW6l+fROMdHIi3bPI8pfv/RexNuo+Lx02WF7R7pHRbKQmN1h3F2cHVFFkxGaArrGAA3lGkqUZLzYd1FD7wL6ziglpxZyQ2Bkhbpn3o84XDaTaJ+W6wOXjkurXkHA2PoeboUE=,iv:jqTNMKxiwh9bW5wZA3ar2NwIK1WiTjyCzkU+45es/qI=,tag:rlu9UkT6XrkCHvTYG5LTSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
