---
apiVersion: v1
kind: Namespace
metadata:
  name: pg
---
apiVersion: v1
kind: Secret
metadata:
    name: database-grafana-password
    namespace: pg
stringData:
    username: ENC[AES256_GCM,data:09stywGO+A==,iv:MymHLM/aTa2HF7tIv7FGXUpfsRW1hfBDYQz9L8lB1ho=,tag:irKWz8n7u7L9rpc3AeKLrQ==,type:str]
    password: ENC[AES256_GCM,data:ge9GgsLXduiRgjNNP2CwUObGY9935qipzRrd9hG2TVbV6ic3C9eDYBSufu92XpZzA7g3AED9dXWgq63gNujSow==,iv:fOlPqpuU1l2I28b2ne3YpZpV3FlGBYutd3xhr1qrsi4=,tag:5oXAY3wCVZZkZeE/Um/XKQ==,type:str]
sops:
    age:
        - recipient: age103f6jf4nhgwlmnn93al2s342se2awnlcsaxuts8eycffgrdwn5ssd57f28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd1JNTnlsYTVWUWJOaWdK
            OFdNU2NxcEg5eW82c1RnQjRIQjVlK2J4SUE4CmhsdnF3TFFnTEpXb1dPc29ZQW1V
            aHFnSUp1NW1WUWtNWlk0R1R6UTVtRmcKLS0tIDBlMTVTL3pCM1RWcWlLK3NudXdC
            VDRpZk55NVpEVEpnZnNoTVovVDZnRWMKqQpx808paXxffjdAKuG3fNRCMO8jvBer
            tPv4uShaQVNeiMEAP9qwuqPLfqPA8xWlDhVS3qvS3aEOb9NCp4ajIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T23:55:03Z"
    mac: ENC[AES256_GCM,data:0FN2sLkUPVIhJ93jG0BmSnsbFK3GqChlh7D8FXbYujahMVgYZQvOXE+IdiD+rrNoLOHLuJr39WZ1zZyMUDAfxTe6sZL3zMhN8DePZrAKjG4RXvpsHhE2eh7KY9t/ZxCG/2TzBVDwLvoAwuZpK9cJ6FDiIyGKd0Sia2SQWsloXOY=,iv:HSykS+WWe3uM9+tKvpqJNGipBCAYFu7lzEqHvlys5v4=,tag:EUihVfYLcwCifIJrZAgkvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
