apiVersion: v1
kind: Secret
metadata:
    name: garage-admin-token
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:Ylu5/vkracL7PNad3GwEuHtTHfWHn92hZHlbzPP8g+Vncmnl+lkxK4N5HyuzhWpn2ULMC0AnLmp47B9w5YXWuw==,iv:FpSeWHt/ia7PaT+dQ6OqEz/wnyjgA0etZz5YoweaIlY=,tag:Uv+3nSG/KeAHDKF2RBJUWA==,type:str]
sops:
    age:
        - recipient: age103f6jf4nhgwlmnn93al2s342se2awnlcsaxuts8eycffgrdwn5ssd57f28
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvK2NEV1B4RzluVG96RjZx
            cUVGeVNEejhmeTJEL01UMXQ4R3lhaGsrOVdzCnZyZXFkdE1xeFR2WEdVREovU0ZX
            ckdSVWFtRG1BMGZmY1RLUk96WW9USk0KLS0tIGZGcXZMVXRUd0l6NW5VQ1lNcmMr
            ajVOZUtmNlFOc2JFZXBiMG1qRExTY1EK3fabDaSfIQsLbP8zpKPA+wfPoZ92Ta/V
            Pzs6c0URPOQejDdG4af4cX939YG/67M+iXOxKhJ9rCU5RMq4nAZI3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T23:55:52Z"
    mac: ENC[AES256_GCM,data:6p/r5dVHMv2aIzoJGTswN4xhB32hjNV3m9gV/pBowqqmmwCB/kiPs2poWnpKKDyUYWumYfrptvk4cw6khxDQqZPEwa9ZfkZWuhQJCyDR0G9fXjYcZmvE9MJKG65EHIlObc1ixrjV+9qhVjC6+gMsjnXXgOo9pMC6FsZwxnnMOzg=,iv:TfhXYzkenPgLanpjX8F+X7/i3hNpRFvlKOkFsPaaItw=,tag:xo0xaL2ptgIryiv86XKVZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
