apiVersion: v1
kind: Secret
metadata:
    name: garage-admin-token
    namespace: default
stringData:
    token: ENC[AES256_GCM,data:0I4TD21g4KzjglqxoiMK/ZdDnfW1q7wSIeuqRNCbXIPIm6TBTm4j1iqF/CpAJCY7oMjQtsFwggr3SMvAiebxpw==,iv:tdHWAfKzKWhF6hfi8HltKw9x/j0Il7a0K3Id09h9Kxs=,tag:S7mHVzZ6VBnsztoGbP0mzg==,type:str]
sops:
    age:
        - recipient: age19akqjue8a6z28csprf9msealft9jj98534jd3fmawelmgwscy44qgacuvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOGRPN2RHQ2p0Mi9IWXMv
            dU5VV1JCdVJWaVJPdkt1NFZFbU56dVI0VDJBCmdWRlE4N2o1QXRmQkY0VnFpKzcw
            WVZ5UlZ3M3BadzlDOWU3eGhIazBqR28KLS0tIHllMnhESkhmTCtzbTZUb3RoN054
            S3gyYVdzeWFmc21YOUp6T2I0ZzBLOXcKZDVNN4+qe3jF6bMgeC5SGAFGZU8nuA0W
            +TQZFzJxxagiLZH7tKYw5mYrq2HvUs0B5xSCSMX1950iVbE8lwZJzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T22:30:28Z"
    mac: ENC[AES256_GCM,data:qYwaLo+JXXGtS9aJo2drVAPkyj6nWZmV7jKCgordaT+XIAI1Vl2SlCEJkifaAugtEItGlQx3ZxthQTJtFQMXan8yDDGJQWQKo0P8OR3kBMiEc+a9G1B6FTtl5Yk4Qmou8uq0e23sp7T9GwdJBwMjhn+cqRmkKyWAymbXTjblIsM=,iv:qdIw9qr3Zp0Ckz7mwA00bmXZ2z5vYBptnDc59k8Pu9A=,tag:salDorg++2KYYKXAX/aZWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
