#!/bin/bash
echo "reset levianthan"
ssh deploy@10.10.0.11 'sudo rm -rf /var/lib/rancher'
ssh deploy@10.10.0.11 'sudo rm -rf /var/lib/kubelet'
ssh deploy@10.10.0.11 'sudo rm -rf /var/lib/longhorn/*'

echo "reset neferu"
ssh deploy@10.10.0.12 'sudo rm -rf /var/lib/rancher'
ssh deploy@10.10.0.12 'sudo rm -rf /var/lib/kubelet'
ssh deploy@10.10.0.12 'sudo rm -rf /var/lib/longhorn/*'

echo "reset nimue"
ssh deploy@10.10.0.13 'sudo rm -rf /var/lib/rancher'
ssh deploy@10.10.0.13 'sudo rm -rf /var/lib/kubelet'
ssh deploy@10.10.0.13 'sudo rm -rf /var/lib/longhorn/*'