name: Build and Push docker image
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Check Nix flake
      uses: DeterminateSystems/flake-checker-action@main

    - name: Install Nix
      uses: DeterminateSystems/determinate-nix-action@main

    - name: Configure Nix cache
      uses: DeterminateSystems/flakehub-cache-action@v2 
      continue-on-error: true
      with:
        diff-store: true

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        nix build .#blockyDns
        docker load < result

    - name: Rename image to match Google Docker registry
      run: |
        docker tag blocky-dns:latest ghcr.io/${{github.repository}}/blocky-dns:latest blocky-dns:latest ghcr.io/${{github.repository}}/blocky-dns:${{ github.sha }}
        # docker tag blocky-dns:latest ghcr.io/${{github.repository}}/blocky-dns:${{ github.sha }}

    - name: Push Docker image
      run: |
        docker push --all-tags
        # docker push ghcr.io/${{github.repository}}/blocky-dns:latest
        # docker push ghcr.io/${{github.repository}}/blocky-dns:${{ github.sha }}
